version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: qdrant
    ports:
      - "6333:6333" # REST API + gRPC
      - "6334:6334" # gRPC only
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__STORAGE__AUTO_FLUSH_INTERVAL: 1 # optional, seconds

volumes:
  qdrant_storage:
